
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class regservice extends javax.swing.JInternalFrame {

    /**
     * Creates new form regservice
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null; 
    
     public regservice() {
        super("Add Service");
        initComponents();
        conn = databaseConnection.connection();
        jTable1.getTableHeader().setDefaultRenderer(new regcustomer.HeaderColor());
               
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        
        
        try{
           stmt = conn.createStatement();
           String sql = "SELECT * FROM service";
           ResultSet res = stmt.executeQuery(sql);
           
            while (res.next()) {
                
                DefaultTableModel dtm = (DefaultTableModel)jTable1.getModel();
                dtm.addRow(new Object[]{res.getString("ServiceID"),res.getString("SName"),res.getString("Price"),res.getString("STime")});                 
            }
           
        }catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jTable1.setGridColor(Color.gray);
        
        
         try {
             String ss = "SELECT COUNT(*) FROM service";
             rs = stmt.executeQuery(ss);
               
            if(rs.next()){
                
               String SID = (rs.getString("COUNT(*)"));
               int SV = Integer.parseInt(SID);
               
               if(SV == 0){
               int no = 1;
               String NO =  String.format("%03d", no);
               serviceid.setText("S" + NO);
               
               }else{
               SV=SV+1;
               String NO =  String.format("%03d", SV);
               serviceid.setText("S" + NO);
               }
               
            }
         } catch (Exception e) {
         }
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        serviceid = new javax.swing.JTextField();
        sname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        stime = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1500, 900));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerservices (2).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Service ID");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Service Name");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Price");

        serviceid.setBackground(new java.awt.Color(230, 231, 232));
        serviceid.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        serviceid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        serviceid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serviceidKeyPressed(evt);
            }
        });

        sname.setBackground(new java.awt.Color(230, 231, 232));
        sname.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        sname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                snameKeyPressed(evt);
            }
        });

        price.setBackground(new java.awt.Color(230, 231, 232));
        price.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        price.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submitebtn.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/submitpur.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updatebtn.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/updateblue.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Service Name", "Price", "Service Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowHeight(25);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("Service Time");

        stime.setBackground(new java.awt.Color(230, 231, 232));
        stime.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        stime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        stime.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stimeKeyPressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SeekPng.com_cogs-png_754228.png"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchbtn3.png"))); // NOI18N
        jButton3.setToolTipText("Click to Search the Service you Want");
        jButton3.setBorder(null);
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/searchpur3.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(stime, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(serviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(48, 48, 48)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6))
                            .addComponent(stime, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(serviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try{
             stmt = conn.createStatement();
             String ServiceID = serviceid.getText();
             String SName = sname.getText();
             String STime = stime.getText();
             Double Price = Double.parseDouble(price.getText());
             
                      String sql1 = "SELECT SName FROM service WHERE SName= '"+sname.getText()+"'";
            rs = stmt.executeQuery(sql1);
              int count = 0;
            while(rs.next()){
                  count++;
              }
              if(count==1){
              JOptionPane.showMessageDialog(null, "Already Exists an Account from these Details!"); 
           
               
              }else{
            
             
             if (ServiceID.hashCode() == 0 || SName.hashCode() == 0 || STime.hashCode() == 0 || Price.hashCode() == 0)
              {
                  JOptionPane.showMessageDialog(null, "Some fields are empty!");
              }
              else
              {
             String sql = " INSERT INTO service(ServiceID, SName, STime, Price) VALUES('"+ServiceID+"', '"+SName+"', '"+STime+"', '"+Price+"')";
               
             stmt.executeUpdate(sql);
             JOptionPane.showMessageDialog(null,"Data is successfully inserted");
                     
           stmt = conn.createStatement();
           String sql3 = "SELECT * FROM service";
           ResultSet res = stmt.executeQuery(sql3);
           jTable1.setModel(DbUtils.resultSetToTableModel(res));
             
           serviceid.setText(null);
           sname.setText(null);
           stime.setText(null);
           price.setText(null);
              }
              
          }
           
            
             String ss = "SELECT COUNT(*) FROM service";
             rs = stmt.executeQuery(ss);
               
            if(rs.next()){
                
               String SID = (rs.getString("COUNT(*)"));
               int SV = Integer.parseInt(SID);
              
               SV=SV+1;
               String NO =  String.format("%03d", SV);
               serviceid.setText("S" + NO);
               
               
            }
         
            
         }catch(HeadlessException | NumberFormatException | SQLException e){
             JOptionPane.showMessageDialog(null, e);
             
        
          
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            stmt = conn.createStatement();
            String ServiceID = serviceid.getText();
            String SName = sname.getText();
            String STime = stime.getText();
            String Price = price.getText();
            
            
            String sql = "UPDATE service SET SName='"+SName+"', STime='"+STime+"', Price='"+Price+"' WHERE ServiceID ='"+ServiceID+"'";

            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data is successfully updated");
            
            
            
           serviceid.setText(null);
           sname.setText(null);
           stime.setText(null);
           price.setText(null);
       
           
           stmt = conn.createStatement();
           String sql3 = "SELECT * FROM service";
           ResultSet res = stmt.executeQuery(sql3);
           jTable1.setModel(DbUtils.resultSetToTableModel(res));
           
        }catch(HeadlessException | NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            stmt = conn.createStatement();

            String ServiceID = serviceid.getText();

            String sql = "SELECT * FROM service WHERE ServiceID ='"+ServiceID+"'";

            rs = stmt.executeQuery(sql);

            if(rs.next()){

                serviceid.setText(rs.getString("ServiceID"));
                sname.setText(rs.getString("SName"));
                stime.setText(rs.getString("STime"));
                price.setText(rs.getString("Price"));

            }else{
                JOptionPane.showMessageDialog(null,"Record not found");
            }

        } catch (HeadlessException | NumberFormatException | SQLException e){JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void serviceidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serviceidKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:price.requestFocus();
                break;
           case 40:sname.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            sname.requestFocus();
        }
    }//GEN-LAST:event_serviceidKeyPressed

    private void snameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:serviceid.requestFocus();
                break;
           case 40:stime.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            stime.requestFocus();
        }
    }//GEN-LAST:event_snameKeyPressed

    private void stimeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stimeKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:sname.requestFocus();
                break;
           case 40:price.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            price.requestFocus();
        }
    }//GEN-LAST:event_stimeKeyPressed

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:stime.requestFocus();
                break;
           case 40:serviceid.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            serviceid.requestFocus();
        }
    }//GEN-LAST:event_priceKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField serviceid;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField stime;
    // End of variables declaration//GEN-END:variables
}
