
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class searchcustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form searchcustomer
     */
     Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null; 
    
    public searchcustomer() {
        super("Search Customer");
        initComponents();
        conn = databaseConnection.connection();
    
        
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cnic = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        cphone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        allergies = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        illness = new javax.swing.JTextField();
        pregnant = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1500, 900));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 900));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Customer NIC");

        cnic.setBackground(new java.awt.Color(230, 231, 232));
        cnic.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        cnic.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicActionPerformed(evt);
            }
        });
        cnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnicKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Customer Name");

        cname.setBackground(new java.awt.Color(230, 231, 232));
        cname.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        cname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cnameKeyPressed(evt);
            }
        });

        cphone.setBackground(new java.awt.Color(230, 231, 232));
        cphone.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        cphone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cphoneActionPerformed(evt);
            }
        });
        cphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cphoneKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setText("Phone Number");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Address");

        address.setBackground(new java.awt.Color(230, 231, 232));
        address.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        address.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("Age");

        age.setBackground(new java.awt.Color(230, 231, 232));
        age.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        age.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setText("Pregnant");

        allergies.setBackground(new java.awt.Color(230, 231, 232));
        allergies.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        allergies.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        allergies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                allergiesKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setText("Allergies");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Chronic Illness");

        illness.setBackground(new java.awt.Color(230, 231, 232));
        illness.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        illness.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        illness.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                illnessKeyPressed(evt);
            }
        });

        pregnant.setBackground(new java.awt.Color(230, 231, 232));
        pregnant.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        pregnant.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pregnant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pregnantKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchbtn1.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/searchpur.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/updatebtn.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/updatepur.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deletebtn.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/deletepur.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search (2).png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(address)
                                            .addComponent(cphone)
                                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(illness, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(83, 83, 83)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pregnant, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(allergies, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(pregnant, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(allergies, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(illness, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cnic, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cphone, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(167, 167, 167)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(0, 92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicActionPerformed

    private void cphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cphoneActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try{
            stmt = conn.createStatement();
            
            String NIC = cnic.getText();
            
            String sql = "SELECT * FROM customer WHERE NIC ='"+NIC+"'";
            
            rs = stmt.executeQuery(sql);
               
            if(rs.next()){
                
                cnic.setText(rs.getString("NIC"));
                cname.setText(rs.getString("CName"));
                cphone.setText(rs.getString("CPhone"));
                address.setText(rs.getString("Address"));
                age.setText(rs.getString("Age"));
                pregnant.setText(rs.getString("Pregnant"));
                allergies.setText(rs.getString("Allergies"));
                illness.setText(rs.getString("ChronicIllness"));
                
                
            }else{
                 JOptionPane.showMessageDialog(null,"Record not found");
            }
                
            } catch (HeadlessException | NumberFormatException | SQLException e){JOptionPane.showMessageDialog(null, e); 
           
        
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            try{
            stmt = conn.createStatement();
            String NIC = cnic.getText();
            String CName = cname.getText();
            String CPhone = cphone.getText();
            String Address = address.getText();
            String Age = age.getText();
            String Pregnant = pregnant.getText();
            String Allergies = allergies.getText();
            String ChronicIllness = illness.getText();
            

            String sql = "UPDATE customer SET NIC ='"+NIC+"', CName='"+CName+"', CPhone='"+CPhone+"', Address='"+Address+"', Age='"+Age+"', Pregnant='"+Pregnant+"', Allergies='"+Allergies+"', ChronicIllness='"+ChronicIllness+"' WHERE NIC='"+NIC+"'";

            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Data is successfully updated");
            
           cnic.setText(null);
           pregnant.setText(null);
           cname.setText(null);
           cphone.setText(null);
           address.setText(null);
           age.setText(null);
           allergies.setText(null);
           illness.setText(null); 
           
        }catch(HeadlessException | NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to Delete?", "Delete",JOptionPane.YES_NO_OPTION);
        if(opt==0){
        try{
           stmt = conn.createStatement();
           String NIC = cnic.getText();
           String sql="DELETE FROM customer WHERE NIC = '"+NIC+"'";
           stmt.executeUpdate(sql);
           JOptionPane.showMessageDialog(null,"Data is successfully Deleted");
           
           cnic.setText(null);
           pregnant.setText(null);
           cname.setText(null);
           cphone.setText(null);
           address.setText(null);
           age.setText(null);
           allergies.setText(null);
           illness.setText(null);
           
        }catch (NumberFormatException | SQLException e){JOptionPane.showMessageDialog(null, e); 
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void cnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnicKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:illness.requestFocus();
                break;
           case 39:pregnant.requestFocus();
                break;    
           case 40:cname.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            cname.requestFocus();
        }
    }//GEN-LAST:event_cnicKeyPressed

    private void cnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:cnic.requestFocus();
                break;
           case 39:allergies.requestFocus();
                break;
           case 40:cphone.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            cphone.requestFocus();
        }
    }//GEN-LAST:event_cnameKeyPressed

    private void cphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cphoneKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:cname.requestFocus();
                break;
           case 39:illness.requestFocus();
                break;
           case 40:address.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            address.requestFocus();
        }
    }//GEN-LAST:event_cphoneKeyPressed

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:cphone.requestFocus();
                break;
           case 39:illness.requestFocus();
                break;
           case 40:age.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            age.requestFocus();
        }
    }//GEN-LAST:event_addressKeyPressed

    private void ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 38:address.requestFocus();
                break;
           case 40:pregnant.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            pregnant.requestFocus();
        }
    }//GEN-LAST:event_ageKeyPressed

    private void pregnantKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pregnantKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 37:cnic.requestFocus();
                break;
           case 38:age.requestFocus();
                break;
           case 40:allergies.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            allergies.requestFocus();
        }
    }//GEN-LAST:event_pregnantKeyPressed

    private void allergiesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_allergiesKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 37:cname.requestFocus();
                break;
           case 38:pregnant.requestFocus();
                break;
           case 40:illness.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            illness.requestFocus();
        }
    }//GEN-LAST:event_allergiesKeyPressed

    private void illnessKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_illnessKeyPressed
        // TODO add your handling code here:
            switch(evt.getKeyCode())
        {
           case 37:cphone.requestFocus();
                break;
           case 38:allergies.requestFocus();
                break;
           case 40:cnic.requestFocus();
                break;
        }
           int key=evt.getKeyCode();
            if(key==10){
            cnic.requestFocus();
        }
    }//GEN-LAST:event_illnessKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField allergies;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField cphone;
    private javax.swing.JTextField illness;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pregnant;
    // End of variables declaration//GEN-END:variables
}
